"""
US High Yield Spread Rich/Cheap Model
======================================
A Streamlit web application that uses rolling multiple linear regression
to determine if US High Yield credit spreads are rich, cheap, or neutral
relative to fundamental market drivers.

Supports dynamic variable intake — any number of independent variables
with feature flags controlling how each is transformed.

Author: Generated by Claude
"""

import streamlit as st
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import StandardScaler
import plotly.graph_objects as go
from plotly.subplots import make_subplots
import io
from datetime import datetime

# ─────────────────────────────────────────────────────────────
# Page config
# ─────────────────────────────────────────────────────────────
st.set_page_config(
    page_title="HY Spread Rich/Cheap Model",
    page_icon="📊",
    layout="wide",
    initial_sidebar_state="expanded",
)

# Custom CSS
st.markdown("""
<style>
    .signal-box {
        padding: 24px; border-radius: 12px; text-align: center;
        margin-bottom: 16px; color: white; font-weight: bold;
    }
    .signal-cheap { background: linear-gradient(135deg, #1b8a3d, #27ae60); }
    .signal-rich  { background: linear-gradient(135deg, #c0392b, #e74c3c); }
    .signal-neutral { background: linear-gradient(135deg, #636e72, #95a5a6); }
    .metric-card {
        background: #f8f9fa; border-radius: 8px; padding: 16px;
        border-left: 4px solid #3498db; margin-bottom: 8px;
    }
    div[data-testid="stSidebar"] { background-color: #f0f2f6; }
</style>
""", unsafe_allow_html=True)


# ─────────────────────────────────────────────────────────────
# Constants for auto-detection
# ─────────────────────────────────────────────────────────────
DATE_ALIASES = ["date"]
HY_SPREAD_ALIASES = [
    "us high yield spread", "hy spread", "hy_spread", "high yield spread",
    "us hy spread", "hy oas", "us high yield oas",
]

VALID_FLAGS = {"L", "LM", "LMP", "MP", "P", "N"}
DEFAULT_FLAG = "LM"

FLAG_DESCRIPTIONS = {
    "L": "Level",
    "LM": "Level + MoM Change",
    "LMP": "Level + MoM Change + % Change",
    "MP": "MoM Change + % Change",
    "P": "% Change",
    "N": "Excluded",
}

# ─────────────────────────────────────────────────────────────
# JPM Historical Default & Recovery Data (Source: JPM Default Monitor)
# Update annually when JPM publishes new figures.
# Recovery rate: HY Bonds. Years without recovery data use 40% fallback.
# ─────────────────────────────────────────────────────────────
_JPM_DEFAULT_RATES = {
    1982: 0.0340, 1983: 0.0160, 1984: 0.0210, 1985: 0.0380, 1986: 0.0350,
    1987: 0.0690, 1988: 0.0280, 1989: 0.0720, 1990: 0.1090, 1991: 0.1150,
    1992: 0.0440, 1993: 0.0230, 1994: 0.0140, 1995: 0.0280, 1996: 0.0160,
    1997: 0.0150, 1998: 0.0170, 1999: 0.0410, 2000: 0.0500, 2001: 0.0910,
    2002: 0.0800, 2003: 0.0330, 2004: 0.0110, 2005: 0.0280, 2006: 0.0090,
    2007: 0.0040, 2008: 0.0230, 2009: 0.1030, 2010: 0.0080, 2011: 0.0170,
    2012: 0.0130, 2013: 0.0070, 2014: 0.0290, 2015: 0.0180, 2016: 0.0360,
    2017: 0.0130, 2018: 0.0180, 2019: 0.0260, 2020: 0.0620, 2021: 0.0030,
    2022: 0.0080, 2023: 0.0210, 2024: 0.0036, 2025: 0.0099,
}
_JPM_RECOVERY_RATES = {                      # HY Bonds; NaN years fall back to 0.40
    1990: 0.3701, 1991: 0.3666, 1992: 0.4919, 1993: 0.3713, 1994: 0.5373,
    1995: 0.4760, 1996: 0.6275, 1997: 0.5610, 1998: 0.4163, 1999: 0.3804,
    2000: 0.2381, 2001: 0.2145, 2002: 0.2969, 2003: 0.4187, 2004: 0.5425,
    2005: 0.5488, 2006: 0.5502, 2007: 0.2102, 2008: 0.3060, 2009: 0.3000,
    2010: 0.4820, 2011: 0.5120, 2012: 0.5290, 2013: 0.5270, 2014: 0.5280,
    2015: 0.3340, 2016: 0.4040, 2017: 0.5770, 2018: 0.3990, 2019: 0.3260,
    2020: 0.2710, 2021: 0.6050, 2022: 0.6000, 2023: 0.4640, 2024: 0.6120,
}
_FALLBACK_RECOVERY = 0.40   # used when year not in _JPM_RECOVERY_RATES


@st.cache_data
def _build_jpm_df():
    """Build a tidy annual DataFrame from JPM constants with loss rate computed."""
    rows = []
    for yr, dr in sorted(_JPM_DEFAULT_RATES.items()):
        rec = _JPM_RECOVERY_RATES.get(yr, _FALLBACK_RECOVERY)
        rows.append({
            "year":      yr,
            "date":      pd.Timestamp(f"{yr}-12-31"),
            "dr":        dr * 100,          # %
            "rec":       rec,
            "loss_rate": dr * (1 - rec) * 100,   # %
        })
    return pd.DataFrame(rows)


def _match_column(df_columns, aliases):
    """Fuzzy-match a DataFrame column against a list of aliases (case-insensitive)."""
    lower_cols = {}
    for c in df_columns:
        try:
            lower_cols[str(c).strip().lower()] = c
        except Exception:
            continue
    for alias in aliases:
        if alias in lower_cols:
            return lower_cols[alias]
    return None


def load_data(uploaded_file):
    """
    Load and validate the uploaded Excel file.

    Expected format:
        Row 1: Column headers
        Row 2: Feature flags (L / LM / LMP / MP / P / N) — blank for Date and HY Spread
        Row 3+: Data

    Returns:
        df: cleaned DataFrame with standardised column names
        dep_var_col: original name of the dependent variable column
        variable_flags: dict mapping {internal_col_name: flag} for independent variables
        original_names: dict mapping {internal_col_name: original_col_name} for display
    """
    # Read the raw file — row 0 = headers, row 1 = flags, rows 2+ = data
    try:
        raw = pd.read_excel(uploaded_file, header=None)
    except Exception as e:
        st.error(f"❌ Could not read Excel file: {e}")
        return None, None, None, None

    if len(raw) < 3:
        st.error("❌ File must have at least 3 rows: headers (row 1), flags (row 2), and data (row 3+).")
        return None, None, None, None

    # Extract headers and flag row
    headers = [str(h).strip() for h in raw.iloc[0]]
    flag_row = [str(f).strip().upper() for f in raw.iloc[1]]

    # Build DataFrame from data rows (row index 2 onward)
    df = raw.iloc[2:].reset_index(drop=True)
    df.columns = headers

    # --- Auto-detect Date column ---
    date_col = _match_column(headers, DATE_ALIASES)
    if date_col is None:
        # Try to find a column that parses as dates
        for h in headers:
            try:
                test = pd.to_datetime(df[h], errors="coerce")
                if test.notna().sum() > len(df) * 0.5:
                    date_col = h
                    break
            except Exception:
                continue
    if date_col is None:
        st.error("❌ Could not find a Date column. Please ensure your first column is named 'Date'.")
        return None, None, None, None

    # --- Auto-detect HY Spread (dependent variable) ---
    dep_var_col = _match_column(headers, HY_SPREAD_ALIASES)
    if dep_var_col is None:
        st.error("❌ Could not find the HY Spread column. Expected one of: " +
                 ", ".join(f"'{a}'" for a in HY_SPREAD_ALIASES))
        return None, None, None, None

    # --- Parse flags for all other columns ---
    header_to_idx = {h: i for i, h in enumerate(headers)}
    variable_flags = {}  # internal_name -> flag
    original_names = {}  # internal_name -> original header

    skip_cols = {date_col, dep_var_col}
    unrecognised_flags = []

    for col_name in headers:
        if col_name in skip_cols:
            continue
        idx = header_to_idx[col_name]
        raw_flag = flag_row[idx] if idx < len(flag_row) else ""

        # Skip columns with no header or nonsense headers
        if col_name.lower() in ("", "nan", "none"):
            continue

        # Parse flag
        if raw_flag in VALID_FLAGS:
            flag = raw_flag
        elif raw_flag in ("", "NAN", "NONE", "NAT"):
            flag = DEFAULT_FLAG  # default if blank
        else:
            unrecognised_flags.append((col_name, raw_flag))
            flag = DEFAULT_FLAG

        # Create a safe internal name (lowercase, underscores)
        internal = col_name.strip().lower().replace(" ", "_").replace("&", "and")
        internal = "".join(c if c.isalnum() or c == "_" else "_" for c in internal)

        variable_flags[internal] = flag
        original_names[internal] = col_name

    if unrecognised_flags:
        flag_list = ", ".join(f"'{col}' → '{f}'" for col, f in unrecognised_flags)
        st.warning(f"⚠️ Unrecognised flags (defaulting to {DEFAULT_FLAG}): {flag_list}. "
                   f"Valid flags: {', '.join(sorted(VALID_FLAGS))}")

    # Filter out all N-flagged columns
    active_vars = {k: v for k, v in variable_flags.items() if v != "N"}
    if not active_vars:
        st.error("❌ All independent variables are flagged 'N' (excluded). At least one variable must be included.")
        return None, None, None, None

    # --- Build clean DataFrame ---
    # Rename to internal names
    rename_map = {date_col: "date", dep_var_col: "hy_spread"}
    for internal, orig in original_names.items():
        rename_map[orig] = internal

    df = df.rename(columns=rename_map)

    # Keep only columns we need
    keep_cols = ["date", "hy_spread"] + list(original_names.keys())
    keep_cols = [c for c in keep_cols if c in df.columns]
    df = df[keep_cols].copy()

    # Convert types
    df["date"] = pd.to_datetime(df["date"], errors="coerce")
    for c in df.columns:
        if c != "date":
            df[c] = pd.to_numeric(df[c], errors="coerce")

    df = df.dropna(subset=["date"]).sort_values("date").reset_index(drop=True)
    df = df.ffill()  # forward-fill minor gaps

    # ── HYG Shares Outstanding scaling ──
    # Divide by 1,000,000 to improve matrix conditioning (large raw values cause numerical instability)
    hyg_aliases = ["hyg_shares_outstanding", "hyg_shares", "hyg_outstanding"]
    for col in df.columns:
        if col.lower().replace(" ", "_") in hyg_aliases or col in hyg_aliases:
            df[col] = df[col] / 1_000_000

    return df, dep_var_col, variable_flags, original_names


def engineer_features(df, variable_flags, original_names, change_on_change=False):
    """
    Create derived features based on each variable's flag.

    Flags:
        L   → level only
        LM  → level + monthly change
        LMP → level + monthly change + % change
        MP  → monthly change + % change
        P   → % change only
        N   → excluded (already filtered out before this call)

    If change_on_change=True:
        - Dependent variable becomes ΔHY Spread (monthly change)
        - All "Level" terms are dropped
        - Variables flagged "L" are promoted to MoM change
        - The model tests whether changes in fundamentals explain changes in spreads

    For flags that generate both MoM change and % change (LMP, MP), both are
    generated here but tracked as competing pairs. The selection of which to
    use happens inside run_regression() on a per-window basis.

    Returns:
        feat_df: DataFrame with date, hy_spread, and all derived feature columns
        feature_cols: list of ALL derived feature column names (including both candidates)
        feature_labels: dict mapping feature_col → display label
        competing_pairs: list of tuples (mom_col, pct_col, var_internal_name) for per-window selection
    """
    feat = df[["date", "hy_spread"]].copy()

    # In change-on-change mode, the dependent variable is ΔHY Spread
    if change_on_change:
        feat["hy_spread_level"] = feat["hy_spread"].copy()  # preserve for display
        feat["hy_spread"] = feat["hy_spread"].diff()

    feature_cols = []
    feature_labels = {}
    competing_pairs = []  # (mom_col, pct_col, var_internal_name)

    for var, flag in variable_flags.items():
        if flag == "N":
            continue
        if var not in df.columns:
            continue

        display_name = original_names.get(var, var)

        if change_on_change:
            # Override flags: drop levels, promote L to MoM change
            has_mom = True  # always generate MoM change
            has_pct = "P" in flag
            # No level terms in change-on-change mode

            col_name = f"{var}_change"
            feat[col_name] = df[var].diff()
            feature_cols.append(col_name)
            feature_labels[col_name] = f"{display_name} MoM Chg"

            if has_pct:
                col_name_p = f"{var}_pct_change"
                feat[col_name_p] = df[var].pct_change() * 100
                feature_cols.append(col_name_p)
                feature_labels[col_name_p] = f"{display_name} % Chg"
                competing_pairs.append((f"{var}_change", f"{var}_pct_change", var))
        else:
            # Original levels-based logic
            # Level
            if "L" in flag:
                col_name = f"{var}_level"
                feat[col_name] = df[var]
                feature_cols.append(col_name)
                feature_labels[col_name] = f"{display_name} Level"

            # Monthly change — flag contains "M"
            has_mom = "M" in flag
            has_pct = "P" in flag

            if has_mom:
                col_name = f"{var}_change"
                feat[col_name] = df[var].diff()
                feature_cols.append(col_name)
                feature_labels[col_name] = f"{display_name} MoM Change"

            # Percentage change — flag contains "P"
            if has_pct:
                col_name = f"{var}_pct_change"
                feat[col_name] = df[var].pct_change() * 100
                feature_cols.append(col_name)
                feature_labels[col_name] = f"{display_name} % Change"

            # Track competing pairs (both MoM and Pct generated)
            if has_mom and has_pct:
                competing_pairs.append((f"{var}_change", f"{var}_pct_change", var))

    feat = feat.dropna().reset_index(drop=True)

    # Replace any remaining inf values from pct_change (e.g., division by zero)
    feat = feat.replace([np.inf, -np.inf], np.nan).dropna().reset_index(drop=True)

    return feat, feature_cols, feature_labels, competing_pairs


# ─────────────────────────────────────────────────────────────
# Regression engine
# ─────────────────────────────────────────────────────────────
def run_regression(feat_df, feature_cols, lookback, competing_pairs=None):
    """
    Run rolling-window OLS regression with per-window feature selection.

    Uses StandardScaler + QR decomposition for numerical stability.
    Coefficients and standard errors are unscaled back to natural units.

    For variables with both MoM change and % change features (competing_pairs),
    at each rolling window the function selects the transformation with higher
    absolute Pearson correlation to HY Spread. Only the winner enters the regression.

    Returns:
        results: DataFrame with predictions, residuals
        model_stats: dict with final-window statistics
        coef_df: DataFrame of coefficient history
        latest_selections: dict mapping var_internal_name → 'mom' or 'pct' (latest window)
        active_feature_cols: list of feature columns actually used in the final window
    """
    from scipy import stats as sp_stats

    if competing_pairs is None:
        competing_pairs = []

    n = len(feat_df)
    if n < lookback + 1:
        st.error(f"Not enough data ({n} rows) for a {lookback}-month lookback window.")
        return None

    X_all = feat_df[feature_cols].values
    y_all = feat_df["hy_spread"].values
    col_index = {c: i for i, c in enumerate(feature_cols)}

    # Identify which feature_cols are always included (not part of a competing pair)
    competing_mom_cols = {mom for mom, pct, var in competing_pairs}
    competing_pct_cols = {pct for mom, pct, var in competing_pairs}
    base_col_indices = [col_index[c] for c in feature_cols
                        if c not in competing_mom_cols and c not in competing_pct_cols]

    predictions = np.full(n, np.nan)
    residuals = np.full(n, np.nan)
    coef_history = []
    latest_selections = {}
    active_feature_cols = None

    for i in range(lookback, n):
        y_train = y_all[i - lookback:i]

        # Per-window feature selection for competing pairs
        window_col_indices = list(base_col_indices)
        window_selections = {}
        window_feature_names = [feature_cols[idx] for idx in base_col_indices]

        for mom_col, pct_col, var in competing_pairs:
            mom_idx = col_index[mom_col]
            pct_idx = col_index[pct_col]
            mom_vals = X_all[i - lookback:i, mom_idx]
            pct_vals = X_all[i - lookback:i, pct_idx]

            # Compute absolute Pearson correlation with HY spread over training window
            valid = ~(np.isnan(mom_vals) | np.isnan(pct_vals) | np.isnan(y_train))
            if valid.sum() < 10:
                window_col_indices.append(mom_idx)
                window_feature_names.append(mom_col)
                window_selections[var] = "mom"
                continue

            mom_corr = abs(np.corrcoef(mom_vals[valid], y_train[valid])[0, 1])
            pct_corr = abs(np.corrcoef(pct_vals[valid], y_train[valid])[0, 1])

            if np.isnan(mom_corr):
                mom_corr = 0.0
            if np.isnan(pct_corr):
                pct_corr = 0.0

            if pct_corr > mom_corr:
                window_col_indices.append(pct_idx)
                window_feature_names.append(pct_col)
                window_selections[var] = "pct"
            else:
                window_col_indices.append(mom_idx)
                window_feature_names.append(mom_col)
                window_selections[var] = "mom"

        # Build training matrix with selected features only
        X_train = X_all[i - lookback:i][:, window_col_indices]

        # Check for NaN in training window
        mask = ~(np.isnan(X_train).any(axis=1) | np.isnan(y_train))
        if mask.sum() < 20:
            continue

        # Use sklearn for rolling predictions (fast, no SE needed per window)
        model = LinearRegression()
        model.fit(X_train[mask], y_train[mask])

        X_pred = X_all[i:i+1][:, window_col_indices]
        pred = model.predict(X_pred)[0]
        predictions[i] = pred
        residuals[i] = y_all[i] - pred
        coef_history.append({
            "idx": i,
            "date": feat_df["date"].iloc[i],
            "intercept": model.intercept_,
            **{f"coef_{c}": v for c, v in zip(window_feature_names, model.coef_)},
        })

        # Track latest window selections
        latest_selections = window_selections
        active_feature_cols = window_feature_names

    results = feat_df.copy()
    results["predicted"] = predictions
    results["residual"] = residuals

    # If no windows ran successfully, bail out
    if active_feature_cols is None:
        st.error("Regression could not produce results for any window.")
        return None

    # ══════════════════════════════════════════════════════════════
    # Final-window statistics with QR decomposition + StandardScaler
    # ══════════════════════════════════════════════════════════════
    last_start = n - lookback
    y_last = y_all[last_start:n]

    # Rebuild the final window's feature selection
    final_col_indices = list(base_col_indices)
    final_feature_names = [feature_cols[idx] for idx in base_col_indices]
    for mom_col, pct_col, var in competing_pairs:
        mom_idx = col_index[mom_col]
        pct_idx = col_index[pct_col]
        if latest_selections.get(var) == "pct":
            final_col_indices.append(pct_idx)
            final_feature_names.append(pct_col)
        else:
            final_col_indices.append(mom_idx)
            final_feature_names.append(mom_col)

    X_last_raw = X_all[last_start:n][:, final_col_indices]
    mask = ~(np.isnan(X_last_raw).any(axis=1) | np.isnan(y_last))
    X_clean = X_last_raw[mask]
    y_clean = y_last[mask]

    n_obs = X_clean.shape[0]
    k = X_clean.shape[1]  # number of features (excl. intercept)
    dof = n_obs - k - 1

    # ── Step 1: Standardise X ──
    # First, detect and remove zero-variance (constant) features in the raw data.
    # StandardScaler sets scale_=1.0 for constant columns (not 0), but produces
    # all-zero scaled columns which cause singularity in QR decomposition.
    raw_std = np.std(X_clean, axis=0, ddof=0)
    valid_feat_mask = raw_std > 1e-12
    if not valid_feat_mask.all():
        X_clean = X_clean[:, valid_feat_mask]
        final_feature_names = [f for f, v in zip(final_feature_names, valid_feat_mask) if v]
        final_col_indices = [idx for idx, v in zip(final_col_indices, valid_feat_mask) if v]
        k = X_clean.shape[1]
        dof = n_obs - k - 1

    scaler = StandardScaler()
    X_scaled = scaler.fit_transform(X_clean)
    x_std = scaler.scale_      # per-feature std dev (σ_j)
    x_mean = scaler.mean_      # per-feature mean (μ_j)

    # Safety: replace any NaN from scaling
    X_scaled = np.nan_to_num(X_scaled, nan=0.0)

    # ── Step 2: Add intercept column and solve via QR decomposition ──
    X_design = np.column_stack([np.ones(n_obs), X_scaled])  # [1 | X_scaled]

    Q, R = np.linalg.qr(X_design, mode='reduced')

    # Solve R @ beta_scaled = Q' @ y  for beta_scaled
    # Use scipy solve_triangular (designed for triangular R) with fallback to lstsq
    Qty = Q.T @ y_clean
    try:
        from scipy.linalg import solve_triangular
        beta_scaled = solve_triangular(R, Qty)
    except (np.linalg.LinAlgError, Exception):
        # Fallback: least-squares solve (handles rank-deficient cases)
        beta_scaled, _, _, _ = np.linalg.lstsq(X_design, y_clean, rcond=None)

    intercept_scaled = beta_scaled[0]
    coefs_scaled = beta_scaled[1:]  # coefficients in standardised-X space

    # ── Step 3: Residuals & sigma (in original y space — y was not scaled) ──
    y_pred_last = X_design @ beta_scaled
    resid = y_clean - y_pred_last
    ss_res = np.sum(resid ** 2)
    ss_tot = np.sum((y_clean - y_clean.mean()) ** 2)
    r2 = 1 - ss_res / ss_tot
    adj_r2 = 1 - (1 - r2) * (n_obs - 1) / max(dof, 1)
    sigma2 = ss_res / max(dof, 1)  # residual variance
    residual_std = np.sqrt(sigma2)

    # ── Step 4: Standard errors in scaled space via (R'R)^-1 ──
    # Var(beta_scaled) = sigma^2 * (R'R)^-1 = sigma^2 * R^-1 * R'^-1
    try:
        from scipy.linalg import solve_triangular
        R_inv = solve_triangular(R, np.eye(R.shape[0]))
    except (np.linalg.LinAlgError, Exception):
        R_inv = np.linalg.pinv(R)
    var_beta_scaled = sigma2 * (R_inv @ R_inv.T)
    se_scaled = np.sqrt(np.maximum(np.diag(var_beta_scaled), 0.0))
    se_scaled_coefs = se_scaled[1:]  # drop intercept SE

    # ── Step 5: Unscale coefficients & SEs back to natural units ──
    # β_natural_j = β_scaled_j / σ_x_j
    coefs_natural = coefs_scaled / x_std

    # SE_natural_j = SE_scaled_j / σ_x_j
    se_natural = se_scaled_coefs / x_std

    # Unscale the intercept: intercept_natural = intercept_scaled - Σ(β_scaled_j * μ_j / σ_j)
    intercept_natural = intercept_scaled - np.sum(coefs_scaled * x_mean / x_std)

    # ── Step 6: t-stats and p-values ──
    t_stats = coefs_natural / np.where(se_natural > 1e-15, se_natural, np.nan)
    p_values = 2 * (1 - sp_stats.t.cdf(np.abs(t_stats), df=max(dof, 1)))

    model_stats = {
        "r2": r2,
        "adj_r2": adj_r2,
        "n_obs": n_obs,
        "residual_std": residual_std,
        "coefficients": coefs_natural,
        "intercept": intercept_natural,
        "std_errors": se_natural,
        "t_stats": t_stats,
        "p_values": p_values,
    }

    coef_df = pd.DataFrame(coef_history)
    return results, model_stats, coef_df, latest_selections, final_feature_names


def calculate_oos_r2(results):
    """
    Calculate out-of-sample R² from rolling one-step-ahead predictions.

    This measures genuine predictive power: how well the model predicts
    the NEXT month's spread using only data available at prediction time.
    Unlike in-sample R² which can be inflated by shared trends, OOS R²
    only rewards actual forecasting ability.

    OOS R² = 1 - SS_res / SS_tot
    where SS_res = sum of squared prediction errors
    and SS_tot = sum of squared deviations from mean actual spread
    """
    valid = results.dropna(subset=["predicted", "hy_spread"]).copy()
    if len(valid) < 3:
        return np.nan

    actual = valid["hy_spread"].values
    predicted = valid["predicted"].values

    ss_res = np.sum((actual - predicted) ** 2)
    ss_tot = np.sum((actual - actual.mean()) ** 2)

    if ss_tot < 1e-15:
        return np.nan

    return 1 - ss_res / ss_tot


def calculate_signals(results, cheap_thresh, rich_thresh, lookback=None):
    """
    Calculate z-scores and trading signals.

    If lookback is provided, the z-score is normalised against the trailing
    `lookback` residuals (consistent with the rolling regression window).
    Otherwise falls back to expanding (full-history) normalisation.
    """
    if lookback is not None:
        # Rolling z-score: each residual normalised against the prior `lookback` residuals
        rolling_mean = results["residual"].rolling(window=lookback, min_periods=20).mean()
        rolling_std = results["residual"].rolling(window=lookback, min_periods=20).std()
        results["z_score"] = (results["residual"] - rolling_mean) / rolling_std
    else:
        # Fallback: full-history normalisation
        valid = results["residual"].dropna()
        mean_r = valid.mean()
        std_r = valid.std()
        results["z_score"] = (results["residual"] - mean_r) / std_r

    def _signal(z):
        if pd.isna(z):
            return "N/A"
        if z > cheap_thresh:
            return "CHEAP"
        if z < -rich_thresh:
            return "RICH"
        return "NEUTRAL"

    results["signal"] = results["z_score"].apply(_signal)
    return results


def monthly_attribution(results, coef_df, feature_cols, feature_labels):
    """
    Calculate factor-level contribution to predicted spread changes.

    Uses a fully reconciling decomposition:
      Predicted_T   = Σ(coef_T × feature_T)   + intercept_T
      Predicted_T-1 = Σ(coef_T-1 × feature_T-1) + intercept_T-1

    The change in predicted spread is decomposed into:
      1. Feature Effect:  coef_T-1 × (feature_T - feature_T-1)
         → contribution from features changing, holding coefficients constant
      2. Model Recalibration: everything else (coef drift + interaction + intercept change)
         → lumped into a single line so the total reconciles exactly

    Returns a DataFrame sorted by absolute contribution (descending) with
    both spread-level and basis-point columns.
    """
    if coef_df is None or coef_df.empty or len(coef_df) < 2:
        return None
    last = coef_df.iloc[-1]
    prev = coef_df.iloc[-2]
    idx_last = int(last["idx"])
    idx_prev = int(prev["idx"])

    # Actual change in predicted spread (the number we must reconcile to)
    pred_last = results["predicted"].iloc[idx_last]
    pred_prev = results["predicted"].iloc[idx_prev]
    if pd.isna(pred_last) or pd.isna(pred_prev):
        return None
    actual_pred_change = pred_last - pred_prev  # in spread % units

    attrib_rows = []
    total_feature_effect = 0.0

    for col in feature_cols:
        coef_key = f"coef_{col}"
        # Need coefficient from PREVIOUS window to compute feature effect
        if coef_key not in prev or coef_key not in last:
            continue
        coef_prev = prev[coef_key]
        coef_last = last[coef_key]
        if pd.isna(coef_prev) and pd.isna(coef_last):
            continue

        # Use previous-period coefficient for the feature effect
        # (holding model constant, how much did feature moves contribute?)
        coef_for_attrib = coef_prev if not pd.isna(coef_prev) else 0.0
        feat_change = results[col].iloc[idx_last] - results[col].iloc[idx_prev]
        contribution = coef_for_attrib * feat_change
        total_feature_effect += contribution

        if coef_for_attrib == 0 and feat_change == 0:
            continue

        attrib_rows.append({
            "Factor": feature_labels.get(col, col),
            "Coefficient": coef_for_attrib,
            "Feature Change": feat_change,
            "Contribution (spread, %)": contribution,
            "Contribution (bps)": contribution * 100,
        })

    if not attrib_rows:
        return None

    # Model Recalibration line: absorbs intercept change + coefficient drift + interaction
    recalib = actual_pred_change - total_feature_effect
    attrib_rows.append({
        "Factor": "Model Recalibration",
        "Coefficient": np.nan,
        "Feature Change": np.nan,
        "Contribution (spread, %)": recalib,
        "Contribution (bps)": recalib * 100,
    })

    attrib = pd.DataFrame(attrib_rows)
    # Sort by absolute impact descending
    attrib = attrib.sort_values("Contribution (bps)", key=abs, ascending=False).reset_index(drop=True)
    total = attrib["Contribution (spread, %)"].sum()
    attrib["% of Total"] = np.where(abs(total) > 1e-10, attrib["Contribution (spread, %)"] / abs(total) * 100, 0)
    return attrib


# ─────────────────────────────────────────────────────────────
# Charts
# ─────────────────────────────────────────────────────────────
def chart_actual_vs_predicted(results):
    fig = go.Figure()
    fig.add_trace(go.Scatter(x=results["date"], y=results["hy_spread"],
                             name="Actual HY Spread", line=dict(color="#2980b9", width=2)))
    fig.add_trace(go.Scatter(x=results["date"], y=results["predicted"],
                             name="Predicted HY Spread", line=dict(color="#e67e22", width=2, dash="dash")))
    fig.update_layout(title="Actual vs Predicted HY Spreads",
                      xaxis_title="Date", yaxis_title="Spread (%)",
                      template="plotly_white", height=450, legend=dict(orientation="h", y=1.12))
    return fig


def chart_residuals(results, cheap_thresh, rich_thresh, lookback=None):
    valid = results.dropna(subset=["residual"]).copy()

    # Compute rolling mean and std for time-varying threshold bands
    if lookback is not None:
        rolling_mean = valid["residual"].rolling(window=lookback, min_periods=20).mean()
        rolling_std = valid["residual"].rolling(window=lookback, min_periods=20).std()
    else:
        # Expanding window fallback
        rolling_mean = valid["residual"].expanding(min_periods=20).mean()
        rolling_std = valid["residual"].expanding(min_periods=20).std()

    cheap_band = rolling_mean + cheap_thresh * rolling_std
    rich_band = rolling_mean - rich_thresh * rolling_std

    fig = go.Figure()
    colors = valid["signal"].map({"CHEAP": "#27ae60", "RICH": "#e74c3c", "NEUTRAL": "#95a5a6", "N/A": "#bdc3c7"})
    fig.add_trace(go.Scatter(x=valid["date"], y=valid["residual"], mode="lines+markers",
                             marker=dict(color=colors, size=5), line=dict(color="#7f8c8d", width=1),
                             name="Residual"))
    fig.add_trace(go.Scatter(x=valid["date"], y=cheap_band, mode="lines",
                             line=dict(color="#27ae60", width=1.5, dash="dash"),
                             name=f"Cheap ({cheap_thresh}σ)"))
    fig.add_trace(go.Scatter(x=valid["date"], y=rich_band, mode="lines",
                             line=dict(color="#e74c3c", width=1.5, dash="dash"),
                             name=f"Rich (-{rich_thresh}σ)"))
    fig.add_trace(go.Scatter(x=valid["date"], y=rolling_mean, mode="lines",
                             line=dict(color="gray", width=1, dash="dot"),
                             name="Rolling Mean"))
    fig.update_layout(title="Residuals Over Time", xaxis_title="Date", yaxis_title="Residual (%)",
                      template="plotly_white", height=400,
                      legend=dict(orientation="h", y=1.12))
    return fig


def chart_zscore(results, cheap_thresh, rich_thresh):
    valid = results.dropna(subset=["z_score"])
    fig = go.Figure()
    colors = valid["signal"].map({"CHEAP": "#27ae60", "RICH": "#e74c3c", "NEUTRAL": "#95a5a6", "N/A": "#bdc3c7"})
    fig.add_trace(go.Bar(x=valid["date"], y=valid["z_score"],
                         marker_color=colors, name="Z-Score"))
    fig.add_hline(y=cheap_thresh, line_dash="dash", line_color="#27ae60",
                  annotation_text=f"Cheap ({cheap_thresh}σ)")
    fig.add_hline(y=-rich_thresh, line_dash="dash", line_color="#e74c3c",
                  annotation_text=f"Rich (-{rich_thresh}σ)")
    fig.add_hline(y=0, line_color="gray", line_width=0.5)
    fig.update_layout(title="Z-Score History", xaxis_title="Date", yaxis_title="Z-Score",
                      template="plotly_white", height=400)
    return fig


def chart_coefficients(model_stats, feature_cols, feature_labels):
    labels = [feature_labels.get(c, c) for c in feature_cols]
    coefs = model_stats["coefficients"]
    colors = ["#27ae60" if c > 0 else "#e74c3c" for c in coefs]
    fig = go.Figure(go.Bar(y=labels, x=coefs, orientation="h",
                           marker_color=colors, text=[f"{c:.4f}" for c in coefs],
                           textposition="outside"))
    # Dynamic height based on number of features
    bar_height = max(420, len(feature_cols) * 35 + 80)
    fig.update_layout(title="Current Regression Coefficients",
                      xaxis_title="Coefficient Value", template="plotly_white",
                      height=bar_height, margin=dict(l=200))
    return fig


# ─────────────────────────────────────────────────────────────
# Excel export
# ─────────────────────────────────────────────────────────────
def generate_excel_report(results, model_stats, raw_df, feat_df, attrib_df,
                          feature_cols, feature_labels, variable_flags, original_names,
                          bey_df=None, bey_ytw_col=None, bey_coupon_col=None, bey_rf_col=None):
    """Generate a multi-sheet Excel workbook."""
    try:
        from openpyxl import Workbook
        from openpyxl.styles import Font, PatternFill, Alignment, numbers, Border, Side
        from openpyxl.utils.dataframe import dataframe_to_rows
    except ImportError:
        st.error("openpyxl not installed.")
        return None

    wb = Workbook()

    header_font = Font(bold=True, color="FFFFFF", size=11)
    header_fill = PatternFill(start_color="2C3E50", end_color="2C3E50", fill_type="solid")
    green_fill = PatternFill(start_color="27AE60", end_color="27AE60", fill_type="solid")
    red_fill = PatternFill(start_color="E74C3C", end_color="E74C3C", fill_type="solid")
    gray_fill = PatternFill(start_color="95A5A6", end_color="95A5A6", fill_type="solid")
    thin_border = Border(
        left=Side(style='thin'), right=Side(style='thin'),
        top=Side(style='thin'), bottom=Side(style='thin')
    )

    def _style_header(ws, ncols):
        for col in range(1, ncols + 1):
            cell = ws.cell(row=1, column=col)
            cell.font = header_font
            cell.fill = header_fill
            cell.alignment = Alignment(horizontal="center")
            cell.border = thin_border

    def _auto_width(ws):
        from openpyxl.utils import get_column_letter
        for col_idx in range(1, ws.max_column + 1):
            max_len = 0
            for row_idx in range(1, ws.max_row + 1):
                cell = ws.cell(row=row_idx, column=col_idx)
                try:
                    max_len = max(max_len, len(str(cell.value or "")))
                except:
                    pass
            col_letter = get_column_letter(col_idx)
            ws.column_dimensions[col_letter].width = min(max_len + 3, 30)

    # --- Sheet 1: Dashboard ---
    ws = wb.active
    ws.title = "Dashboard"
    latest = results.dropna(subset=["z_score"]).iloc[-1]
    ws.append(["HY Spread Rich/Cheap Model — Dashboard"])
    ws.merge_cells("A1:D1")
    ws["A1"].font = Font(bold=True, size=16)
    ws.append([])
    ws.append(["Generated", datetime.now().strftime("%Y-%m-%d %H:%M")])
    ws.append(["Latest Data Date", latest["date"].strftime("%Y-%m-%d")])
    ws.append([])
    ws.append(["CURRENT SIGNAL", latest["signal"]])
    sig_cell = ws.cell(row=6, column=2)
    sig_cell.font = Font(bold=True, color="FFFFFF", size=14)
    if latest["signal"] == "CHEAP":
        sig_cell.fill = green_fill
    elif latest["signal"] == "RICH":
        sig_cell.fill = red_fill
    else:
        sig_cell.fill = gray_fill
    ws.append([])
    ws.append(["Metric", "Value"])
    metrics = [
        ("Actual HY Spread", f"{latest['hy_spread']:.2f}%"),
        ("Predicted HY Spread", f"{latest['predicted']:.2f}%"),
        ("Residual", f"{latest['residual']:.2f}%"),
        ("Z-Score", f"{latest['z_score']:.2f}"),
        ("R²", f"{model_stats['r2']:.4f}"),
        ("Adj R²", f"{model_stats['adj_r2']:.4f}"),
        ("Features Used", str(len(feature_cols))),
    ]
    for label, val in metrics:
        ws.append([label, val])
    _auto_width(ws)

    # --- Sheet 2: Data Input ---
    ws2 = wb.create_sheet("Data Input")
    raw_export = raw_df.copy()
    raw_export["date"] = raw_export["date"].dt.strftime("%Y-%m-%d")
    for r in dataframe_to_rows(raw_export, index=False, header=True):
        ws2.append(r)
    _style_header(ws2, len(raw_export.columns))
    _auto_width(ws2)

    # --- Sheet 3: Calculated Features ---
    ws3 = wb.create_sheet("Calculated Features")
    feat_export = feat_df.copy()
    feat_export["date"] = feat_export["date"].dt.strftime("%Y-%m-%d")
    for r in dataframe_to_rows(feat_export, index=False, header=True):
        ws3.append(r)
    _style_header(ws3, len(feat_export.columns))
    _auto_width(ws3)

    # --- Sheet 4: Model Statistics ---
    ws4 = wb.create_sheet("Model Statistics")
    ws4.append(["Feature", "Coefficient", "Std Error", "T-Statistic", "P-Value"])
    _style_header(ws4, 5)
    for i, col in enumerate(feature_cols):
        ws4.append([
            feature_labels.get(col, col),
            round(float(model_stats["coefficients"][i]), 6),
            round(float(model_stats["std_errors"][i]), 6),
            round(float(model_stats["t_stats"][i]), 4),
            round(float(model_stats["p_values"][i]), 6),
        ])
    ws4.append([])
    ws4.append(["Intercept", round(float(model_stats["intercept"]), 6)])
    ws4.append(["R²", round(float(model_stats["r2"]), 6)])
    ws4.append(["Adjusted R²", round(float(model_stats["adj_r2"]), 6)])
    ws4.append(["Observations", int(model_stats["n_obs"])])
    ws4.append(["Residual Std Dev", round(float(model_stats["residual_std"]), 6)])
    _auto_width(ws4)

    # --- Sheet 5: Variable Configuration ---
    ws_vars = wb.create_sheet("Variable Config")
    ws_vars.append(["Variable", "Flag", "Derived Features"])
    _style_header(ws_vars, 3)
    for var, flag in variable_flags.items():
        display = original_names.get(var, var)
        desc = FLAG_DESCRIPTIONS.get(flag, flag)
        ws_vars.append([display, flag, desc])
    _auto_width(ws_vars)

    # --- Sheet 6: Historical Signals ---
    ws5 = wb.create_sheet("Historical Signals")
    hist = results.dropna(subset=["predicted"])[["date", "hy_spread", "predicted", "residual", "z_score", "signal"]].copy()
    hist["date"] = hist["date"].dt.strftime("%Y-%m-%d")
    hist.columns = ["Date", "HY Spread", "Predicted", "Residual", "Z-Score", "Signal"]
    for r in dataframe_to_rows(hist, index=False, header=True):
        ws5.append(r)
    _style_header(ws5, 6)
    for row in range(2, ws5.max_row + 1):
        sig = ws5.cell(row=row, column=6).value
        if sig == "CHEAP":
            ws5.cell(row=row, column=6).fill = PatternFill(start_color="C8E6C9", fill_type="solid")
        elif sig == "RICH":
            ws5.cell(row=row, column=6).fill = PatternFill(start_color="FFCDD2", fill_type="solid")
    _auto_width(ws5)

    # --- Sheet 7: Instructions ---
    ws6 = wb.create_sheet("Instructions")
    instructions = [
        ["How to Interpret This Model"],
        [""],
        ["This model uses rolling multiple linear regression to predict US High Yield spreads"],
        ["based on user-configured market factors with dynamic feature engineering."],
        [""],
        ["Feature Flags (Row 2 of input file):"],
        ["L = Level only"],
        ["LM = Level + Month-over-Month Change"],
        ["LMP = Level + Month-over-Month Change + Percentage Change"],
        ["MP = Month-over-Month Change + Percentage Change"],
        ["P = Percentage Change only"],
        ["N = Exclude variable from model"],
        [""],
        ["Key Concepts:"],
        ["- Predicted Spread: the model's 'fair value' estimate for HY spreads"],
        ["- Residual: Actual minus Predicted (positive = wider than expected)"],
        ["- Z-Score: standardized residual (how many standard deviations from average)"],
        [""],
        ["Signals:"],
        ["- CHEAP: Z-Score above the cheap threshold — spreads are wider than expected"],
        ["  (potential buying opportunity)"],
        ["- RICH: Z-Score below the negative rich threshold — spreads are tighter than expected"],
        ["  (potential selling/hedging opportunity)"],
        ["- NEUTRAL: Z-Score between thresholds — no strong signal"],
        [""],
        ["Asymmetric Thresholds:"],
        ["The model uses different thresholds for RICH vs CHEAP because selling HY bonds"],
        ["means giving up carry income (4-6% per year). A stronger signal is required to"],
        ["justify selling (RICH) compared to buying (CHEAP)."],
    ]
    for row in instructions:
        ws6.append(row)
    ws6["A1"].font = Font(bold=True, size=14)
    _auto_width(ws6)

    # --- Sheet 8: BEY Panel ---
    if bey_df is not None and bey_ytw_col and bey_coupon_col and bey_rf_col:
        ws_bey = wb.create_sheet("BEY Panel")
        ws_bey.append(["Break-Even Yield Panel — Altman-Bencivenga (1995)"])
        ws_bey.merge_cells("A1:G1")
        ws_bey["A1"].font = Font(bold=True, size=14)
        ws_bey.append([])
        ws_bey.append([
            "Date", "HY YTW (%)", "Risk-Free (%)", "Avg Coupon (%)",
            "BEY-Selected (%)", "Premium-Selected (bps)", "Implied DR (%)",
            "BEY-Benign 1.5% (%)", "Premium-Benign (bps)",
            "BEY-Cycle 2.5% (%)", "Premium-Cycle (bps)",
            "BEY-Stressed 4.0% (%)", "Premium-Stressed (bps)",
        ])
        _style_header(ws_bey, 13)
        for _, row in bey_df.iterrows():
            ws_bey.append([
                row["date"].strftime("%Y-%m-%d") if hasattr(row["date"], "strftime") else str(row["date"]),
                round(float(row[bey_ytw_col]), 3),
                round(float(row[bey_rf_col]), 3),
                round(float(row[bey_coupon_col]), 3),
                round(float(row["bey"]), 3),
                round(float(row["premium_bps"]), 1),
                round(float(row["implied_dr"]), 2) if not np.isnan(row["implied_dr"]) else "",
                round(float(row["bey_benign"]), 3),
                round(float(row["premium_bps_benign"]), 1),
                round(float(row["bey_cycle"]), 3),
                round(float(row["premium_bps_cycle"]), 1),
                round(float(row["bey_stressed"]), 3),
                round(float(row["premium_bps_stressed"]), 1),
            ])
        # Colour premium cells green/red
        for row_idx in range(4, ws_bey.max_row + 1):
            for col_idx in [6, 9, 11, 13]:  # premium bps columns
                cell = ws_bey.cell(row=row_idx, column=col_idx)
                try:
                    val = float(cell.value) if cell.value != "" else None
                    if val is not None and val > 0:
                        cell.fill = PatternFill(start_color="C8E6C9", fill_type="solid")
                    elif val is not None and val < 0:
                        cell.fill = PatternFill(start_color="FFCDD2", fill_type="solid")
                except (TypeError, ValueError):
                    pass
        _auto_width(ws_bey)

    buf = io.BytesIO()
    wb.save(buf)
    buf.seek(0)
    return buf


# ─────────────────────────────────────────────────────────────
# Break-Even Yield (Altman-Bencivenga) Panel
# ─────────────────────────────────────────────────────────────

# Column aliases for BEY panel inputs — matched against original header names
_YTW_ALIASES     = {"us hy ytw", "hy ytw", "hy yield to worst", "us hy yield to worst",
                    "high yield ytw", "us hy yld to worst", "hy yld to worst"}
_COUPON_ALIASES  = {"us hy coupon", "hy coupon", "hy avg coupon", "us hy avg coupon",
                    "high yield coupon", "hy average coupon", "us hy average coupon"}
_RF_ALIASES      = {"us 10s", "us 10y", "us 10y treasury yield", "us 10yr",
                    "us 10 year", "us treasury 10y", "10y treasury", "us 10y yield"}


def _detect_bey_columns(original_names):
    """Return (ytw_col, coupon_col, rf_col) internal names, or None for each if not found."""
    ytw_col = coupon_col = rf_col = None
    for internal, orig in original_names.items():
        key = orig.strip().lower()
        if key in _YTW_ALIASES:
            ytw_col = internal
        elif key in _COUPON_ALIASES:
            coupon_col = internal
        elif key in _RF_ALIASES:
            rf_col = internal
    return ytw_col, coupon_col, rf_col


@st.cache_data
def calculate_bey_panel(raw_df, original_names, default_rate, recovery_rate=0.40):
    """
    Compute Altman-Bencivenga Break-Even Yield and yield premium for every month.

    BEY_t = [ Rf_t  +  Df*(1-Rec)  +  Df*(HYC_t/2) ]  /  (1 - Df)

    Premium_t = HY_YTW_t - BEY_t   (positive = spreads are cheap vs fundamentals)

    Implied default rate (back-solved from AHY = BEY):
        Df_implied = (AHY - Rf) / (AHY + (1-Rec) + HYC/2)

    All inputs are in % units (e.g. 7.4 for 7.4%); converted to decimals internally.

    Returns (bey_df, ytw_col, coupon_col, rf_col).
    bey_df is None if required columns are absent.
    """
    ytw_col, coupon_col, rf_col = _detect_bey_columns(original_names)

    if any(c is None for c in (ytw_col, coupon_col, rf_col)):
        return None, ytw_col, coupon_col, rf_col

    missing = [c for c in (ytw_col, coupon_col, rf_col) if c not in raw_df.columns]
    if missing:
        return None, ytw_col, coupon_col, rf_col

    bey_df = raw_df[["date", ytw_col, coupon_col, rf_col]].copy().dropna().reset_index(drop=True)

    # Convert % → decimal for calculation
    ytw    = bey_df[ytw_col]    / 100
    coupon = bey_df[coupon_col] / 100
    rf     = bey_df[rf_col]     / 100

    Df  = default_rate  / 100
    Rec = recovery_rate

    # Selected-assumption BEY and premium
    bey_decimal          = (rf + Df * (1 - Rec) + Df * coupon / 2) / (1 - Df)
    bey_df["bey"]        = bey_decimal * 100
    bey_df["premium"]    = bey_df[ytw_col] - bey_df["bey"]          # %
    bey_df["premium_bps"] = bey_df["premium"] * 100                  # bps

    # Implied default rate
    denom = ytw + (1 - Rec) + coupon / 2
    bey_df["implied_dr"] = np.where(denom > 0, (ytw - rf) / denom * 100, np.nan)

    # Three fixed-scenario BEY lines (for chart reference)
    for label, dr_pct in [("benign", 1.5), ("cycle", 2.5), ("stressed", 4.0)]:
        dr_d = dr_pct / 100
        bey_s = (rf + dr_d * (1 - Rec) + dr_d * coupon / 2) / (1 - dr_d)
        bey_df[f"bey_{label}"]         = bey_s * 100
        bey_df[f"premium_bps_{label}"] = (bey_df[ytw_col] - bey_df[f"bey_{label}"]) * 100

    return bey_df, ytw_col, coupon_col, rf_col


def chart_bey_premium(bey_df, ytw_col, default_rate):
    """Two-panel chart: YTW vs BEY scenarios (top) | Premium in bps (bottom)."""
    fig = make_subplots(
        rows=2, cols=1,
        subplot_titles=(
            "HY Yield to Worst vs Break-Even Yield (three default-rate scenarios)",
            f"Yield Premium vs BEY — {default_rate:.1f}% default rate assumption (bps)",
        ),
        vertical_spacing=0.13,
        row_heights=[0.55, 0.45],
    )

    # Top: absolute yield levels
    fig.add_trace(go.Scatter(
        x=bey_df["date"], y=bey_df[ytw_col],
        name="HY Yield to Worst", line=dict(color="#2980b9", width=2.5)), row=1, col=1)
    fig.add_trace(go.Scatter(
        x=bey_df["date"], y=bey_df["bey_benign"],
        name="BEY — 1.5% DR (benign)", line=dict(color="#27ae60", width=1.3, dash="dot")), row=1, col=1)
    fig.add_trace(go.Scatter(
        x=bey_df["date"], y=bey_df["bey_cycle"],
        name="BEY — 2.5% DR (cycle avg)", line=dict(color="#f39c12", width=1.3, dash="dash")), row=1, col=1)
    fig.add_trace(go.Scatter(
        x=bey_df["date"], y=bey_df["bey_stressed"],
        name="BEY — 4.0% DR (stressed)", line=dict(color="#e74c3c", width=1.3, dash="longdash")), row=1, col=1)

    # Bottom: premium bars for selected assumption
    colors = ["#27ae60" if v >= 0 else "#e74c3c" for v in bey_df["premium_bps"]]
    fig.add_trace(go.Bar(
        x=bey_df["date"], y=bey_df["premium_bps"],
        name=f"Premium ({default_rate:.1f}% DR)", marker_color=colors,
        showlegend=True), row=2, col=1)
    fig.add_hline(y=0, line_color="black", line_width=0.8, row=2, col=1)

    fig.update_layout(
        template="plotly_white", height=580,
        legend=dict(
            orientation="v",
            x=1.02, y=1,
            xanchor="left", yanchor="top",
            bgcolor="rgba(255,255,255,0.8)",
            bordercolor="#cccccc", borderwidth=1,
        ),
        margin=dict(t=60, r=220),
    )
    fig.update_yaxes(title_text="Yield (%)", row=1, col=1)
    fig.update_yaxes(title_text="Premium (bps)", row=2, col=1)
    return fig

def chart_default_rate_history(bey_df, implied_dr_col="implied_dr"):
    """
    Overlay chart combining:
      - Annual JPM historical default rate (bars, full height)
      - Annual JPM credit loss rate = DR × (1 – recovery) (bars, stacked inside DR)
      - Monthly model-implied default rate from BEY calculation (line)
      - Long-run and post-GFC average reference lines

    Bars represent the annual JPM actuals; the line is the market's forward
    pricing of default risk derived from current HY yields.
    """
    jpm = _build_jpm_df()

    # ── Reference line values ──
    full_cycle_avg  = jpm["dr"].mean()          # 1982–2025
    post_gfc_avg    = jpm[jpm["year"] >= 2010]["dr"].mean()

    fig = go.Figure()

    # ── Bar layer 1: total default rate (light blue, full bar height) ──
    # Stacked on top of loss_rate to reach the full DR height.
    # Label describes what the FULL bar represents.
    recovery_portion = jpm["dr"] - jpm["loss_rate"]
    fig.add_trace(go.Bar(
        x=jpm["date"], y=recovery_portion,
        base=jpm["loss_rate"],
        name="Default Rate (total bar)",
        marker_color="rgba(41,128,185,0.30)",
        marker_line_width=0,
        hovertemplate="<b>%{x|%Y}</b><br>Default Rate: %{customdata[0]:.2f}%<br>Recovery Rate: %{customdata[1]:.1%}<extra></extra>",
        customdata=list(zip(jpm["dr"], jpm["rec"])),
    ))

    # ── Bar layer 2: credit loss portion (bottom — darker shade) ──
    fig.add_trace(go.Bar(
        x=jpm["date"], y=jpm["loss_rate"],
        name="Credit Loss Rate (DR × (1 – Rec))",
        marker_color="rgba(41,128,185,0.80)",
        marker_line_width=0,
        hovertemplate="<b>%{x|%Y}</b><br>Loss Rate: %{y:.2f}%<extra></extra>",
    ))

    # ── Reference lines ──
    fig.add_hline(
        y=full_cycle_avg, line_dash="dot", line_color="#7f8c8d", line_width=1.2,
        annotation_text=f"Full-cycle avg {full_cycle_avg:.1f}%",
        annotation_position="top right", annotation_font_size=11,
    )
    fig.add_hline(
        y=post_gfc_avg, line_dash="dash", line_color="#95a5a6", line_width=1.2,
        annotation_text=f"Post-GFC avg {post_gfc_avg:.1f}%",
        annotation_position="bottom right", annotation_font_size=11,
    )

    # ── Implied default rate line (monthly, from model) ──
    if bey_df is not None and implied_dr_col in bey_df.columns:
        impl = bey_df.dropna(subset=[implied_dr_col])
        fig.add_trace(go.Scatter(
            x=impl["date"], y=impl[implied_dr_col],
            name="Model-Implied Default Rate (BEY)",
            line=dict(color="#e74c3c", width=2.2),
            mode="lines",
            hovertemplate="<b>%{x|%b %Y}</b><br>Implied DR: %{y:.1f}%<extra></extra>",
        ))

    fig.update_layout(
        barmode="stack",
        title=dict(
            text="JPM Annual HY Default & Credit Loss Rates vs Model-Implied Default Rate",
            font=dict(size=14),
        ),
        xaxis_title="Year",
        yaxis_title="Rate (%)",
        template="plotly_white",
        height=430,
        legend=dict(orientation="h", y=1.10, x=0),
        margin=dict(t=80),
        hovermode="x unified",
    )
    return fig


# ─────────────────────────────────────────────────────────────
# Streamlit App
# ─────────────────────────────────────────────────────────────
def main():
    # ── Sidebar ──
    st.sidebar.image("https://img.icons8.com/color/96/combo-chart.png", width=60)
    st.sidebar.title("HY Rich/Cheap Model")
    st.sidebar.markdown("---")

    uploaded_file = st.sidebar.file_uploader(
        "📁 Upload Excel Data",
        type=["xlsx"],
        help="Upload a .xlsx file with Row 1 = headers, Row 2 = feature flags (L/LM/LMP/MP/P/N), Row 3+ = data."
    )

    st.sidebar.markdown("### ⚙️ Model Settings")
    model_mode = st.sidebar.radio(
        "Model Specification",
        options=["Standard (flag-based)", "Change-on-Change"],
        index=0,
        help="**Standard:** HY Spread *level* as dependent variable. Independent variables "
             "use transformations from your Row 2 flags (L/LM/LMP/MP/P).\n\n"
             "**Change-on-Change:** ΔHY Spread (monthly change) as dependent variable. "
             "All level terms dropped; all independent variables use MoM changes "
             "(with pct change as competing pair where flagged). Lower R² but more "
             "statistically robust."
    )
    use_changes = model_mode == "Change-on-Change"

    lookback = st.sidebar.select_slider(
        "Lookback Period (months)",
        options=[36, 48, 60],
        value=60,
        help="Number of months used in the rolling regression window."
    )
    cheap_thresh = st.sidebar.slider(
        "Cheap Threshold (σ)", 0.5, 2.0, 1.0, 0.1,
        help="Z-score above this → CHEAP signal (buy). Lower = more sensitive."
    )
    rich_thresh = st.sidebar.slider(
        "Rich Threshold (σ)", 1.0, 3.0, 1.5, 0.1,
        help="Z-score below negative of this → RICH signal (sell). Default 1.5σ calibrated for strategic institutional allocators."
    )

    st.sidebar.markdown("---")
    st.sidebar.markdown("### ⚖️ BEY Panel Settings")
    bey_default_rate = st.sidebar.slider(
        "Default Rate Assumption (%)", 0.5, 6.0, 2.5, 0.1,
        help=(
            "Annual HY default rate used for Break-Even Yield calculation.\n\n"
            "**JPM benchmarks (1982–2025):**\n"
            "- Current LTM (Mar-26): ~1.2% excl. distressed exchanges\n"
            "- Post-GFC average (2010–2025): 1.8%\n"
            "- Full-cycle average (1982–2025): 3.3%\n"
            "- Altman (1995) calibration: 4.1%"
        )
    )
    st.sidebar.caption("Recovery rate fixed at 40% (Altman/JPM historical)")

    st.sidebar.markdown("---")

    # ── Main Panel ──
    st.title("📊 US High Yield Spread — Rich/Cheap Model")
    if use_changes:
        st.caption("⚡ **Change-on-Change mode** — regressing ΔHY Spread on Δ(variables). "
                   "Level terms dropped; all variables use MoM changes.")

    if uploaded_file is None:
        st.info("👈 Upload your Excel data file in the sidebar to get started.")
        with st.expander("ℹ️ About This Model"):
            st.markdown("""
            This tool runs a **rolling multiple linear regression** to estimate the "fair value"
            of US High Yield credit spreads based on market factors you define.

            **Dynamic Variable Support:** The model accepts any number of independent variables.
            Use Row 2 of your Excel file to control how each variable is transformed:

            | Flag | Features Generated |
            |------|--------------------|
            | `L`  | Level only |
            | `LM` | Level + Month-over-Month Change |
            | `LMP`| Level + MoM Change + % Change |
            | `MP` | MoM Change + % Change |
            | `P`  | % Change only |
            | `N`  | Exclude from model |

            The **HY Spread** column is auto-detected as the dependent variable.
            The **Date** column is auto-detected. All other columns are treated as
            candidate independent variables.
            """)
        return

    # Load data
    result = load_data(uploaded_file)
    if result[0] is None:
        return
    raw_df, dep_var_col, variable_flags, original_names = result

    # Initialise BEY panel variables — always defined so the Excel export
    # section never hits a NameError even if the BEY section exits early.
    bey_df = ytw_col_bey = coupon_col_bey = rf_col_bey = None

    # Show detected configuration in sidebar
    st.sidebar.markdown("---")
    st.sidebar.markdown("### 📋 Detected Variables")
    st.sidebar.markdown(f"**Dependent:** {dep_var_col}")
    active_count = sum(1 for f in variable_flags.values() if f != "N")
    excluded_count = sum(1 for f in variable_flags.values() if f == "N")
    st.sidebar.markdown(f"**Independent:** {active_count} active, {excluded_count} excluded")
    with st.sidebar.expander("Variable Details", expanded=False):
        for var, flag in variable_flags.items():
            display = original_names.get(var, var)
            icon = "🟢" if flag != "N" else "🔴"
            st.markdown(f"{icon} **{display}** → `{flag}` ({FLAG_DESCRIPTIONS.get(flag, flag)})")

    # Feature engineering
    feat_df, feature_cols, feature_labels, competing_pairs = engineer_features(
        raw_df, variable_flags, original_names, change_on_change=use_changes
    )

    if len(feature_cols) == 0:
        st.error("❌ No features were generated. Check your feature flags.")
        return

    if len(feat_df) < lookback + 5:
        st.error(f"Not enough data ({len(feat_df)} rows after feature engineering) for {lookback}-month lookback.")
        return

    # Run model
    with st.spinner("Running rolling regression..."):
        reg_result = run_regression(feat_df, feature_cols, lookback, competing_pairs)

    if reg_result is None or reg_result[0] is None:
        return

    results, model_stats, coef_df, latest_selections, active_feature_cols = reg_result
    results = calculate_signals(results, cheap_thresh, rich_thresh, lookback)

    # Build active feature_labels for the selected features only
    active_feature_labels = {c: feature_labels.get(c, c) for c in active_feature_cols}

    # ── Sidebar: Feature selection info (Change 1) ──
    if competing_pairs:
        st.sidebar.markdown("---")
        st.sidebar.markdown("### 🔀 Feature Selection")
        st.sidebar.caption("Per-window auto-selection (latest window):")
        for mom_col, pct_col, var in competing_pairs:
            display_name = original_names.get(var, var)
            sel = latest_selections.get(var, "mom")
            if sel == "pct":
                st.sidebar.markdown(f"**{display_name}:** % Change selected *(MoM dropped)*")
            else:
                st.sidebar.markdown(f"**{display_name}:** MoM Change selected *(% dropped)*")

    # ── Sidebar: Coefficient summary (Change 3) ──
    st.sidebar.markdown("---")
    st.sidebar.markdown("### 📊 Coefficients (Latest Window)")
    for i, col in enumerate(active_feature_cols):
        label = active_feature_labels.get(col, col)
        coef_val = model_stats["coefficients"][i]
        sign = "+" if coef_val >= 0 else ""
        st.sidebar.markdown(f"**{label}:** `{sign}{coef_val:.4f}`")

    # ── Section 1: Current Signal ──
    latest = results.dropna(subset=["z_score"]).iloc[-1]
    prev_rows = results.dropna(subset=["z_score"])
    prev_signal = prev_rows.iloc[-2]["signal"] if len(prev_rows) >= 2 else "N/A"

    signal = latest["signal"]
    css_class = {"CHEAP": "signal-cheap", "RICH": "signal-rich"}.get(signal, "signal-neutral")
    st.markdown(f"""
    <div class="signal-box {css_class}">
        <div style="font-size:14px; opacity:0.85;">Current Signal as of {latest['date'].strftime('%B %d, %Y')}</div>
        <div style="font-size:42px; margin:8px 0;">{signal}</div>
        <div style="font-size:18px;">Z-Score: {latest['z_score']:.2f}</div>
    </div>
    """, unsafe_allow_html=True)

    # ── Section 2: Key Metrics ──
    oos_r2 = calculate_oos_r2(results)

    col1, col2, col3, col4 = st.columns(4)
    if use_changes:
        col1.metric("Actual ΔHY Spread", f"{latest['hy_spread']:+.2f}%")
        col2.metric("Predicted ΔSpread", f"{latest['predicted']:+.2f}%")
    else:
        col1.metric("Actual HY Spread", f"{latest['hy_spread']:.2f}%")
        col2.metric("Predicted Spread", f"{latest['predicted']:.2f}%")
    col3.metric("Residual", f"{latest['residual']:+.2f}%")
    col4.metric("In-Sample R²", f"{model_stats['r2']:.3f}")

    col5, col6, col7, col8 = st.columns(4)
    col5.metric("Z-Score", f"{latest['z_score']:+.2f}")
    col6.metric("Signal", signal)
    col7.metric("OOS R²", f"{oos_r2:.3f}" if not np.isnan(oos_r2) else "N/A",
                help="Out-of-sample R² from rolling one-step-ahead predictions. "
                     "This is the honest measure of predictive power.")
    col8.metric("Adj. R²", f"{model_stats['adj_r2']:.3f}")

    st.markdown("---")

    # ── Section 3: Charts ──
    st.subheader("📈 Interactive Charts")

    tab1, tab2, tab3, tab4 = st.tabs([
        "Actual vs Predicted", "Residuals", "Z-Score History", "Factor Coefficients"
    ])

    with tab1:
        fig_avp = chart_actual_vs_predicted(results)
        if use_changes:
            fig_avp.update_layout(title="Actual vs Predicted ΔHY Spread (MoM Change)",
                                  yaxis_title="Spread Change (%)")
        st.plotly_chart(fig_avp, use_container_width=True)
    with tab2:
        st.plotly_chart(chart_residuals(results, cheap_thresh, rich_thresh, lookback), use_container_width=True)
    with tab3:
        st.plotly_chart(chart_zscore(results, cheap_thresh, rich_thresh), use_container_width=True)
    with tab4:
        st.plotly_chart(chart_coefficients(model_stats, active_feature_cols, active_feature_labels), use_container_width=True)

    st.markdown("---")

    # ── Section 4: Commentary & Monthly Attribution ──
    st.subheader("📝 Commentary & Attribution")
    attrib = monthly_attribution(results, coef_df, active_feature_cols, active_feature_labels)
    if attrib is not None and len(attrib) > 0:
        # Net move = actual change in predicted spread (fully reconciled)
        net_move = attrib["Contribution (bps)"].sum()

        # Separate factor contributions from model recalibration
        factor_attrib = attrib[attrib["Factor"] != "Model Recalibration"]
        recalib_row = attrib[attrib["Factor"] == "Model Recalibration"]
        recalib_bps = recalib_row["Contribution (bps)"].iloc[0] if len(recalib_row) > 0 else 0.0

        top = factor_attrib.head(3)

        # Build automated narrative
        lines = [
            f"**Net Model Move:** The model's fair-value spread "
            f"moved by **{net_move:+.1f} bps** this month."
        ]

        driver_labels = ["Primary Driver", "Secondary Driver", "Tertiary Driver"]
        for i, label in enumerate(driver_labels):
            if i < len(top):
                row = top.iloc[i]
                lines.append(
                    f"**{label}:** {row['Factor']} "
                    f"({row['Contribution (bps)']:+.1f} bps)"
                )

        # Show recalibration if material
        if abs(recalib_bps) >= 0.5:
            lines.append(
                f"**Model Recalibration:** {recalib_bps:+.1f} bps "
                f"(coefficient drift + intercept change from rolling window shift)"
            )

        lines.append(
            f"**Signal Status:** Spreads are currently **{signal}** "
            f"with a Z-Score of **{latest['z_score']:.2f}** "
            f"(R²: {model_stats['r2']:.3f})."
        )

        st.info("\n\n".join(lines))

        # Detailed attribution — filtered to >= 0.5 bps absolute impact
        material = attrib[attrib["Contribution (bps)"].abs() >= 0.5].copy()

        with st.expander(f"🔍 Detailed Factor Attribution ({len(material)} material factors)", expanded=False):
            if len(material) > 0:
                def _fmt(val, fmt_str):
                    if pd.isna(val):
                        return "—"
                    return fmt_str.format(val)

                st.dataframe(
                    material[["Factor", "Coefficient", "Feature Change",
                              "Contribution (spread, %)", "Contribution (bps)", "% of Total"]].style.format({
                        "Coefficient": lambda v: _fmt(v, "{:.6f}"),
                        "Feature Change": lambda v: _fmt(v, "{:.4f}"),
                        "Contribution (spread, %)": "{:+.4f}",
                        "Contribution (bps)": "{:+.1f}",
                        "% of Total": "{:+.1f}%",
                    }),
                    use_container_width=True,
                )
            else:
                st.caption("No factors with impact ≥ 0.5 bps this month.")

        # Transparency note for filtered noise
        noise_count = len(attrib) - len(material)
        if noise_count > 0:
            st.caption(f"ℹ️ {noise_count} factor(s) with < 0.5 bps impact hidden.")
    else:
        st.info("Attribution data not yet available (requires at least 2 regression windows).")

    # ── Section 5: BEY Fundamental Anchor ──
    st.markdown("---")
    st.subheader("⚖️ Fundamental Anchor — Break-Even Yield Premium")

    try:
        import traceback as _tb

        st.caption(
            "Based on Altman & Bencivenga (1995). Asks: given expected defaults and recoveries, "
            "is the market offering adequate compensation? Complements the OLS z-score signal with a "
            "bottom-up fundamental valuation anchor."
        )

        bey_df, ytw_col_bey, coupon_col_bey, rf_col_bey = calculate_bey_panel(
            raw_df, original_names, bey_default_rate
        )

        if bey_df is not None and len(bey_df) > 0:
            lb = bey_df.iloc[-1]

            # ── Metric row ──
            c1, c2, c3, c4 = st.columns(4)
            c1.metric("HY Yield to Worst", f"{lb[ytw_col_bey]:.2f}%",
                      help="Bloomberg HY index yield-to-worst (absolute yield, not spread)")
            c2.metric(f"Break-Even Yield ({bey_default_rate:.1f}% DR)", f"{lb['bey']:.2f}%",
                      help="Minimum yield required to break even vs Treasuries at the selected default rate assumption")
            prem_bps = lb["premium_bps"]
            c3.metric(
                "Yield Premium", f"{prem_bps:+.0f} bps",
                delta="Cheap vs BEY" if prem_bps >= 0 else "Rich vs BEY",
                delta_color="normal" if prem_bps >= 0 else "inverse",
                help="Positive = HY is offering more than required to compensate for default risk (cheap). "
                     "Negative = HY is not covering default risk compensation (rich)."
            )
            c4.metric("Implied Default Rate", f"{lb['implied_dr']:.1f}%",
                      help="The annual default rate the market is implicitly pricing given current "
                           "YTW vs risk-free rate. Compare to: current LTM ~1.2%, post-GFC avg 1.8%, "
                           "full-cycle avg 3.3% (JPM 1982–2025).")

            # ── Scenario comparison row ──
            st.markdown("**Premium across default-rate scenarios:**")
            sc1, sc2, sc3 = st.columns(3)
            for col_st, label, key in [
                (sc1, "Benign — 1.5% DR", "benign"),
                (sc2, "Cycle Avg — 2.5% DR", "cycle"),
                (sc3, "Stressed — 4.0% DR", "stressed"),
            ]:
                p = lb[f"premium_bps_{key}"]
                col_st.metric(
                    label, f"{p:+.0f} bps",
                    delta="Cheap vs BEY" if p >= 0 else "Rich vs BEY",
                    delta_color="normal" if p >= 0 else "inverse",
                )

            # ── Charts ──
            st.plotly_chart(chart_bey_premium(bey_df, ytw_col_bey, bey_default_rate), use_container_width=True)
            st.plotly_chart(chart_default_rate_history(bey_df), use_container_width=True)
            st.caption(
                "Bars show JPM annual HY default rates: dark blue = credit loss rate (DR × (1–recovery)); "
                "full bar height = total default rate. "
                "Red line = market-implied default rate from BEY model (monthly). "
                "Reference lines: full-cycle avg 3.3% (1982–2025), post-GFC avg 1.8% (2010–2025). "
                "Recovery rates: JPM actuals 1990–2024; 40% fallback for 1982–1989 and 2025."
            )

            # ── Interpretation narrative ──
            implied_dr    = float(lb["implied_dr"])
            ytw_now       = float(lb[ytw_col_bey])
            bey_now       = float(lb["bey"])
            rf_now        = float(lb[rf_col_bey])
            coupon_now    = float(lb[coupon_col_bey])
            prem_benign   = float(lb["premium_bps_benign"])
            prem_cycle    = float(lb["premium_bps_cycle"])
            prem_stressed = float(lb["premium_bps_stressed"])

            # Historical premium context — where does today sit in the distribution?
            hist_prem = bey_df["premium_bps"].dropna()
            prem_pctile = int((hist_prem < prem_bps).mean() * 100)
            hist_min    = hist_prem.min()
            hist_max    = hist_prem.max()
            hist_median = hist_prem.median()

            # Implied DR vs benchmarks
            dr_vs_ltm      = implied_dr - 1.2    # vs JPM Mar-26 LTM
            dr_vs_postgfc  = implied_dr - 1.8    # vs post-GFC avg
            dr_vs_cycle    = implied_dr - 3.3    # vs full-cycle avg

            # Directional language helpers
            def _vs(val, label):
                sign = "above" if val > 0 else "below"
                return f"{abs(val):.1f}pp {sign} {label}"

            # Premium adequacy read
            if prem_bps > 200:
                adequacy = "materially generous"
                adequacy_detail = (
                    "The spread cushion is well in excess of what is required to compensate "
                    "for historical default losses. This is the zone typically associated with "
                    "post-crisis dislocations when risk aversion has overshot fundamentals."
                )
            elif prem_bps > 100:
                adequacy = "comfortably adequate"
                adequacy_detail = (
                    "Investors are being paid a meaningful buffer above the minimum required "
                    "to break even against expected defaults. HY offers genuine fundamental "
                    "value at this level."
                )
            elif prem_bps > 0:
                adequacy = "marginally adequate"
                adequacy_detail = (
                    "The market is offering just enough to cover expected default losses, "
                    "but the buffer is thin. Spreads could move rich quickly if default "
                    "expectations rise modestly."
                )
            elif prem_bps > -100:
                adequacy = "marginally insufficient"
                adequacy_detail = (
                    "At current yields, investors are not fully compensated for expected "
                    "default losses on the historical-average default rate assumption. The "
                    "market is implicitly assuming a more benign default environment than "
                    "the long-run average warrants."
                )
            else:
                adequacy = "materially insufficient"
                adequacy_detail = (
                    "Spreads are meaningfully below the level required to compensate for "
                    "default risk on any reasonable assumption. This is the zone associated "
                    "with late-cycle spread compression, where carry is attractive but "
                    "downside asymmetry is elevated."
                )

            # Implied DR interpretation
            if implied_dr < 1.5:
                dr_read = (
                    f"an exceptionally benign default environment — below even the current "
                    f"LTM rate of ~1.2% and well inside the post-GFC average of 1.8%. "
                    f"This level is consistent with a soft-landing / no-recession base case."
                )
            elif implied_dr < 2.5:
                dr_read = (
                    f"a mild default cycle — broadly consistent with the post-GFC average "
                    f"of 1.8% and the current LTM rate of ~1.2%, suggesting the market is "
                    f"pricing modest but not severe credit stress."
                )
            elif implied_dr < 4.0:
                dr_read = (
                    f"a moderate default cycle — above the post-GFC average (1.8%) but "
                    f"below the full-cycle mean (3.3%). The market is pricing meaningful "
                    f"credit deterioration without pricing a recession-level default wave."
                )
            elif implied_dr < 7.0:
                dr_read = (
                    f"a significant default cycle — at or above the full-cycle average "
                    f"of 3.3% and approaching recession-era levels. The market is pricing "
                    f"material credit stress, consistent with late-cycle or recessionary conditions."
                )
            else:
                dr_read = (
                    f"an extreme stress scenario — approaching GFC-era levels (2009: 10.3%, "
                    f"1991: 11.5%). This level of implied default pricing is historically "
                    f"associated with acute financial system stress, not just a credit cycle turn."
                )

            # Scenario robustness commentary
            all_positive = prem_benign > 0 and prem_cycle > 0 and prem_stressed > 0
            two_positive = sum([prem_benign > 0, prem_cycle > 0, prem_stressed > 0]) >= 2
            if all_positive:
                scenario_read = (
                    f"Importantly, the premium is **positive across all three default-rate "
                    f"scenarios** — including the stressed 4.0% assumption. This means HY "
                    f"offers fundamental value even if the default cycle deteriorates "
                    f"materially from current levels."
                )
            elif two_positive:
                scenario_read = (
                    f"The premium is positive under the benign (1.5%) and cycle-average "
                    f"(2.5%) scenarios, but turns negative under the stressed (4.0%) "
                    f"assumption. Fundamental value holds unless defaults rise sharply "
                    f"above current levels."
                )
            else:
                scenario_read = (
                    f"The premium is negative under the cycle-average and stressed "
                    f"scenarios, suggesting current spreads only offer adequate compensation "
                    f"if the default environment remains unusually benign."
                )

            st.info(
                f"**Fundamental Read — {lb['date'].strftime('%B %Y')}**\n\n"
                f"**What this model measures:** The Break-Even Yield (BEY) is the minimum "
                f"yield the HY market must offer for investors to break even against "
                f"Treasuries after accounting for expected default losses and recoveries. "
                f"It is computed as: BEY = [Risk-Free Rate + Default Rate × (1 − Recovery) "
                f"+ Default Rate × (Avg Coupon / 2)] / (1 − Default Rate). "
                f"The *Yield Premium* is simply the difference between the market's actual "
                f"yield-to-worst ({ytw_now:.2f}%) and this break-even hurdle "
                f"({bey_now:.2f}% at {bey_default_rate:.1f}% default rate assumption). "
                f"A positive premium means investors are being more than adequately "
                f"compensated for default risk; a negative premium means they are not.\n\n"
                f"**Current assessment — compensation is {adequacy}:** "
                f"At a {bey_default_rate:.1f}% default rate assumption (40% recovery rate), "
                f"the HY market is offering a yield premium of **{prem_bps:+.0f} bps** "
                f"above break-even. {adequacy_detail} "
                f"Within the available data history, today's premium sits at the "
                f"**{prem_pctile}th percentile** (range: {hist_min:+.0f} to "
                f"{hist_max:+.0f} bps; median: {hist_median:+.0f} bps).\n\n"
                f"**What the market is implying — and why this is consistent with the premium above:** "
                f"The BEY framework can be run in reverse: rather than asking 'does the "
                f"current yield adequately compensate for a {bey_default_rate:.1f}% default rate?', "
                f"we can ask 'what default rate is the market implicitly pricing, given the "
                f"current yield of {ytw_now:.2f}%?' Back-solving the formula gives an implied "
                f"default rate of **{implied_dr:.1f}%** — meaning the market is priced as if "
                f"HY issuers will default at a rate of {implied_dr:.1f}% *every year in "
                f"perpetuity*. Your selected assumption of {bey_default_rate:.1f}% per annum "
                f"in perpetuity is lower than this, which is why a positive premium exists — "
                f"if you believed {implied_dr:.1f}% was the correct long-run default rate, "
                f"the premium would be approximately zero (break-even). These two readings are "
                f"therefore telling the same story from different angles: the market is pricing "
                f"a more pessimistic default environment than your {bey_default_rate:.1f}% "
                f"assumption, and the premium represents the gap between those two views. "
                f"In absolute terms, a market-implied rate of {implied_dr:.1f}% represents "
                f"{dr_read}\n\n"
                f"**Scenario robustness:** To test how sensitive this conclusion is to the "
                f"default rate assumption, the model also computes the yield premium under "
                f"three fixed reference scenarios — a *benign* case of 1.5% per annum "
                f"(near the current JPM LTM rate of ~1.2%), a *cycle-average* case of 2.5% "
                f"(between the post-GFC mean of 1.8% and the full-cycle mean of 3.3%), and "
                f"a *stressed* case of 4.0% (near the JPM full-cycle mean of 3.3% and "
                f"Altman's original 1995 calibration of 4.1%). {scenario_read}\n\n"
                f"*Methodology: Altman & Bencivenga (1995). Recovery rate fixed at 40% "
                f"(conservative vs JPM 1990–2024 mean of 44%). The default rate assumption "
                f"in this model represents a constant annual rate applied in perpetuity — "
                f"it is not a point-in-time forecast. User-selectable via the sidebar slider.*"
            )

            # ── Historical BEY table ──
            with st.expander("📋 Historical BEY & Premium Table", expanded=False):
                disp = bey_df[["date", ytw_col_bey, rf_col_bey, coupon_col_bey,
                               "bey", "premium_bps", "implied_dr"]].copy()
                disp.columns = ["Date", "YTW (%)", "Risk-Free (%)", "Avg Coupon (%)",
                                "BEY (%)", "Premium (bps)", "Implied DR (%)"]

                def _bey_row_style(row):
                    prem = row["Premium (bps)"]
                    colour = "#c8e6c9" if prem > 0 else ("#ffcdd2" if prem < 0 else "")
                    return [f"background-color: {colour}" if colour else "" for _ in row]

                st.dataframe(
                    disp.sort_values("Date", ascending=False).style.format({
                        "Date": lambda x: x.strftime("%Y-%m-%d"),
                        "YTW (%)": "{:.2f}",
                        "Risk-Free (%)": "{:.2f}",
                        "Avg Coupon (%)": "{:.2f}",
                        "BEY (%)": "{:.2f}",
                        "Premium (bps)": "{:+.0f}",
                        "Implied DR (%)": "{:.1f}",
                    }).apply(_bey_row_style, axis=1),
                    use_container_width=True,
                    height=380,
                )
        else:
            missing = []
            if ytw_col_bey is None:
                missing.append("HY Yield to Worst (e.g. 'US HY YTW')")
            if coupon_col_bey is None:
                missing.append("HY Avg Coupon (e.g. 'US HY Coupon')")
            if rf_col_bey is None:
                missing.append("US 10Y Yield (e.g. 'US 10s')")
            st.info(
                f"ℹ️ BEY Panel requires these columns in your Excel file (flagged `N`): "
                f"{', '.join(missing) if missing else 'columns not found in data'}."
            )

    except Exception:
        st.error("**BEY Panel error — full traceback (share this to get a fix):**")
        st.code(_tb.format_exc())

    # ── Section 6: Regression Statistics ──
    with st.expander("📋 Regression Statistics", expanded=False):
        stats_df = pd.DataFrame({
            "Feature": [active_feature_labels.get(c, c) for c in active_feature_cols],
            "Coefficient": model_stats["coefficients"],
            "Std Error": model_stats["std_errors"],
            "T-Statistic": model_stats["t_stats"],
            "P-Value": model_stats["p_values"],
        })
        # Sort by absolute T-Statistic (most significant first)
        stats_df = stats_df.sort_values("T-Statistic", key=abs, ascending=False).reset_index(drop=True)
        st.dataframe(
            stats_df.style.format({
                "Coefficient": "{:.6f}",
                "Std Error": "{:.6f}",
                "T-Statistic": "{:.3f}",
                "P-Value": "{:.4f}",
            }).apply(lambda x: ["background-color: #fff3cd" if v < 0.05 else "" for v in x], subset=["P-Value"]),
            use_container_width=True,
        )

        c1, c2, c3, c4 = st.columns(4)
        c1.metric("Intercept", f"{model_stats['intercept']:.4f}")
        c2.metric("In-Sample R²", f"{model_stats['r2']:.4f}")
        c3.metric("OOS R²", f"{oos_r2:.4f}" if not np.isnan(oos_r2) else "N/A")
        c4.metric("Residual Std", f"{model_stats['residual_std']:.4f}")

        # Diagnostic info
        with st.expander("🔧 SE Diagnostics", expanded=False):
            st.markdown(f"**n_obs:** {model_stats['n_obs']}  |  "
                        f"**k (features):** {len(active_feature_cols)}  |  "
                        f"**dof:** {model_stats['n_obs'] - len(active_feature_cols) - 1}")
            st.markdown(f"**Residual Std (σ):** {model_stats['residual_std']:.10f}")
            st.markdown(f"**σ² = 0?** {model_stats['residual_std'] == 0}")
            st.markdown(f"**Std Errors:** {[f'{v:.10f}' for v in model_stats['std_errors']]}")
            st.markdown(f"**Any SE = 0?** {any(model_stats['std_errors'] == 0)}")
            st.markdown(f"**Features used:** {active_feature_cols}")

    # ── Section 7: Historical Signals ──
    with st.expander("📅 Historical Signals Table", expanded=False):
        hist = results.dropna(subset=["predicted"])[["date", "hy_spread", "predicted", "residual", "z_score", "signal"]].copy()
        hist.columns = ["Date", "HY Spread", "Predicted", "Residual", "Z-Score", "Signal"]

        def _color_signal(val):
            if val == "CHEAP":
                return "background-color: #c8e6c9; color: #1b5e20;"
            elif val == "RICH":
                return "background-color: #ffcdd2; color: #b71c1c;"
            return ""

        st.dataframe(
            hist.style.format({
                "Date": lambda x: x.strftime("%Y-%m-%d"),
                "HY Spread": "{:.2f}",
                "Predicted": "{:.2f}",
                "Residual": "{:+.3f}",
                "Z-Score": "{:+.2f}",
            }).map(_color_signal, subset=["Signal"]),
            use_container_width=True,
            height=400,
        )

    # ── Section 8: Investment Conclusion ──
    st.markdown("---")
    st.subheader("🎯 Investment Conclusion")

    try:
        # ── Gather all inputs ──
        z_score       = float(latest["z_score"])
        actual_spread = float(latest["hy_spread"])
        pred_spread   = float(latest["predicted"])
        residual_pct  = float(latest["residual"])
        residual_bps  = residual_pct * 100
        r2            = float(model_stats["r2"])
        as_of         = latest["date"].strftime("%B %Y")
        data_years    = round((results["date"].max() - results["date"].min()).days / 365.25, 0)

        # Attribution: top driver this month (primary driver label + bps)
        _attrib_tmp = monthly_attribution(results, coef_df, active_feature_cols, active_feature_labels)
        _material   = _attrib_tmp[_attrib_tmp["Contribution (bps)"].abs() >= 0.5].copy()
        _material   = _material.sort_values("Contribution (bps)", key=abs, ascending=False)
        net_move_bps = _attrib_tmp["Contribution (bps)"].sum()
        top_driver   = _material.iloc[0]["Factor"] if len(_material) > 0 else "N/A"
        top_driver_bps = float(_material.iloc[0]["Contribution (bps)"]) if len(_material) > 0 else 0.0

        # OLS signal language
        if signal == "CHEAP":
            ols_read = (
                f"The macro fair-value model rates spreads as **CHEAP** (z-score: "
                f"{z_score:+.2f}), with actual spreads of {actual_spread*100:.0f}bps "
                f"sitting {abs(residual_bps):.0f}bps **wider** than the model's "
                f"fair-value estimate of {pred_spread*100:.0f}bps. "
                f"The macro environment warrants spread compression from here."
            )
            ols_conviction = "positive"
        elif signal == "RICH":
            ols_read = (
                f"The macro fair-value model rates spreads as **RICH** (z-score: "
                f"{z_score:+.2f}), with actual spreads of {actual_spread*100:.0f}bps "
                f"sitting {abs(residual_bps):.0f}bps **tighter** than the model's "
                f"fair-value estimate of {pred_spread*100:.0f}bps. "
                f"The macro environment does not support current spread levels."
            )
            ols_conviction = "negative"
        else:
            direction = "tighter" if residual_bps < 0 else "wider"
            ols_read = (
                f"The macro fair-value model rates spreads as **NEUTRAL** (z-score: "
                f"{z_score:+.2f}), with actual spreads of {actual_spread*100:.0f}bps "
                f"sitting {abs(residual_bps):.0f}bps {direction} than the model's "
                f"fair-value estimate of {pred_spread*100:.0f}bps — "
                f"within the neutral band but on the {'rich' if residual_bps < 0 else 'cheap'} side."
            )
            ols_conviction = "cautious" if residual_bps < 0 else "mildly constructive"

        # Net model move context
        move_dir = "wider" if net_move_bps > 0 else "tighter"
        move_context = (
            f"The model's fair-value spread moved {move_dir} by "
            f"**{abs(net_move_bps):.0f}bps** this month, driven primarily by "
            f"{top_driver} ({top_driver_bps:+.0f}bps)."
        )

        # BEY language — only if available
        if bey_df is not None and len(bey_df) > 0:
            lb_s = bey_df.iloc[-1]
            _prem_bps_s    = float(lb_s["premium_bps"])
            _implied_dr_s  = float(lb_s["implied_dr"])
            _prem_stressed = float(lb_s["premium_bps_stressed"])
            _prem_pctile_s = int((bey_df["premium_bps"].dropna() < _prem_bps_s).mean() * 100)
            _hist_median_s = float(bey_df["premium_bps"].dropna().median())

            bey_intro = (
                f"The fundamental BEY model independently confirms this read: "
                f"at a {bey_default_rate:.1f}% default rate assumption, HY is offering "
                f"**{_prem_bps_s:+.0f}bps** above break-even — a premium sitting at "
                f"just the **{_prem_pctile_s}th percentile** of the available "
                f"~{int(data_years)}-year history (median: {_hist_median_s:+.0f}bps). "
                f"A note on that history: the data window is heavily influenced by "
                f"the GFC era, when spreads — and therefore BEY premiums — reached "
                f"extreme levels; the long-run median will compress as that period "
                f"recedes and as more benign post-2010 years dominate the sample. "
                f"The market is implying a perpetual annual default rate of "
                f"**{_implied_dr_s:.1f}%** — "
                f"{'above' if _implied_dr_s > bey_default_rate else 'below'} the "
                f"{bey_default_rate:.1f}% assumption, which is why the premium is "
                f"{'positive' if _prem_bps_s > 0 else 'negative'}: the two readings "
                f"are the same model viewed from opposite directions."
            )

            if _prem_stressed > 0:
                bey_scenario = (
                    f"Importantly, the premium remains positive even under the stressed "
                    f"4.0% default scenario (+{_prem_stressed:.0f}bps), suggesting "
                    f"adequate — if thin — fundamental value survives a material "
                    f"deterioration in the default cycle."
                )
            else:
                bey_scenario = (
                    f"Under the stressed 4.0% default scenario the premium turns "
                    f"negative ({_prem_stressed:+.0f}bps), meaning fundamental "
                    f"compensation is contingent on defaults remaining contained — "
                    f"a risk worth monitoring in the current macro environment."
                )

            # Combined signal read
            if signal == "CHEAP" and _prem_bps_s > 100:
                combined = (
                    f"Both frameworks are in alignment: macro and fundamental signals "
                    f"are both constructive, providing higher-conviction support for "
                    f"adding HY exposure at current spread levels."
                )
            elif signal == "CHEAP" and _prem_bps_s > 0:
                combined = (
                    f"The macro model is constructive and the fundamental premium is "
                    f"positive, but thin. The directional case for HY exists, though "
                    f"the margin of safety on a fundamental basis is limited."
                )
            elif signal == "NEUTRAL" and _prem_bps_s > 0:
                combined = (
                    f"The two frameworks present a coherent but cautiously positioned "
                    f"picture: spreads are fairly valued on a macro basis, and the "
                    f"fundamental premium — while positive — offers a narrow cushion. "
                    f"For long-term allocators, the current entry point warrants "
                    f"patience: the fundamental case exists, but the margin of safety "
                    f"is narrow and macro volatility indicators are already elevated."
                )
            elif signal == "NEUTRAL" and _prem_bps_s <= 0:
                combined = (
                    f"The macro model is neutral and the fundamental premium has "
                    f"turned negative — a rare combination that warrants caution. "
                    f"HY is neither offering a spread cushion on a macro basis nor "
                    f"adequate default compensation on a fundamental basis."
                )
            elif signal == "RICH":
                combined = (
                    f"Both frameworks are cautionary. The macro model flags spreads "
                    f"as rich relative to the current environment, and the thin "
                    f"fundamental premium offers limited buffer against any "
                    f"deterioration in either macro conditions or default expectations."
                )
            else:
                combined = (
                    f"The two frameworks present a mixed picture that warrants "
                    f"careful monitoring before committing additional risk."
                )

            conclusion_text = (
                f"{ols_read} {move_context}\n\n"
                f"{bey_intro} {bey_scenario}\n\n"
                f"**Overall:** {combined}"
            )

        else:
            # OLS-only conclusion (no BEY data)
            conclusion_text = (
                f"{ols_read} {move_context}\n\n"
                f"*(BEY fundamental panel unavailable — upload HY YTW and "
                f"Avg Coupon columns for a full cross-framework conclusion.)*"
            )

        st.markdown(
            f"<div style='background:#f0f7ff; border-left:4px solid #2980b9; "
            f"border-radius:6px; padding:20px 24px; font-size:15px; line-height:1.7;'>"
            f"{conclusion_text.replace(chr(10), '<br>')}"
            f"</div>",
            unsafe_allow_html=True,
        )
        st.caption(
            f"Signal as of {as_of}. OLS model: {int(data_years)}-year rolling window "
            f"(R²: {r2:.3f}). BEY: Altman-Bencivenga (1995), "
            f"{bey_default_rate:.1f}% default rate, 40% recovery rate."
            if bey_df is not None else
            f"Signal as of {as_of}. OLS model R²: {r2:.3f}."
        )

    except Exception:
        import traceback as _tb3
        st.warning("Investment conclusion could not be generated.")
        st.code(_tb3.format_exc())

    # ── Excel Download ──
    st.markdown("---")
    try:
        import traceback as _tb2
        attrib = monthly_attribution(results, coef_df, active_feature_cols, active_feature_labels)
        excel_buf = generate_excel_report(
            results, model_stats, raw_df, feat_df, attrib,
            active_feature_cols, active_feature_labels, variable_flags, original_names,
            bey_df=bey_df if bey_df is not None else None,
            bey_ytw_col=ytw_col_bey, bey_coupon_col=coupon_col_bey, bey_rf_col=rf_col_bey,
        )
        if excel_buf:
            st.download_button(
                "📥 Download Excel Report",
                data=excel_buf,
                file_name=f"HY_RichCheap_Report_{datetime.now().strftime('%Y%m%d')}.xlsx",
                mime="application/vnd.openxmlformats-officedocument.spreadsheetml.ml.sheet",
            )
    except Exception:
        st.error("**Excel export error — full traceback:**")
        st.code(_tb2.format_exc())


if __name__ == "__main__":
    main()
